# Generated by Django 4.0.6 on 2024-04-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_local_nascimento_autor_nacionalidade_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='data_nascimento',
            new_name='ano_nascimento',
        ),
    ]
