# Generated by Django 4.0.6 on 2024-06-02 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_area_cientifica_curso_curso_area_cientifica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='area_cientifica',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='cursos.curso'),
            preserve_default=False,
        ),
    ]
