# Generated by Django 4.0.6 on 2024-06-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_remove_disciplina_curso_curso_disciplinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.area_cientifica'),
        ),
    ]
