# Generated by Django 4.0.6 on 2024-06-02 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_disciplina_area_cientifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='area_cientifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.area_cientifica'),
        ),
    ]
