# Generated by Django 4.0.6 on 2024-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_album_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='ano',
            new_name='ano_lancamento',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='banda',
            old_name='idade',
            new_name='ano_criacao',
        ),
        migrations.RenameField(
            model_name='musicas',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='album',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='banda',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='musicas',
            name='link',
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
    ]
