# Generated by Django 4.0.6 on 2024-04-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_rename_ano_album_ano_lancamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicas',
            name='duracao',
            field=models.CharField(default='???', max_length=100),
        ),
    ]
