# Generated by Django 4.0.6 on 2024-06-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_alter_album_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicas',
            name='letra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
