# Generated by Django 4.0.6 on 2024-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texto',
            field=models.TextField(default='Descricao Indisponivel'),
            preserve_default=False,
        ),
    ]
